"""add local path to repositories

Revision ID: 21df0eda874d
Revises: c3f6a9e7b1d2
Create Date: 2026-07-27 16:01:57.288824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21df0eda874d'
down_revision: Union[str, Sequence[str], None] = 'c3f6a9e7b1d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('local_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'local_path')
    # ### end Alembic commands ###
